#+TITLE: Architectural Briefing Documentation Template
#+AUTHOR: Christian Romney
#+DATE: 2025-07-08
#+STARTUP: overview
#+OPTIONS: toc:2 num:nil
#+PROPERTY: header-args :mkdirp yes
* Architecture
** What Is This?
A categorical description of the service, for example: "{{name}} is a logging service...".

** What Problem(s) Does It Strive to Solve?
This is the most important part of the document! We need to build services that solve our problems. A good service is clearly pointed at solving one or a few problems. When summarizing a service that you did not build, try to put yourself in the shoes of those who did. What was their mission, what problem(s) were they taking on, and how did they intend to distinguish their solution from others? Try to avoid this being a list of features without connecting those features to problems.

** Core Abstractions
What is it about? A good service has a few clearly defined abstractions around which you can build an understanding of its facilities.

** Primary Operations
Similarly, a good service has a few well-defined operations (endpoints, Kafka topics, etc) that can be composed into solutions.

** Architectural Components
Are there multiple processes, services or components involved, and how do they fit together? Are there environmental (AWS) or supportive (Kafka, Zookeeper) requirements? Diagrams are welcome here.

** Is it Simple?
In the [[https://www.youtube.com/watch?v=LKtk3HCgTa8]["Simple Made Easy"]] sense: is the service complex? Is it stateful? Is it free of [[https://en.wikipedia.org/wiki/Circular_dependency][dependency cycles]] with other services?

** Fundamental Trade-Offs                                           :optional:
Every project has benefits but no project is free of tradeoffs. We need to be explicit about tradeoffs in order to make good decisions, and to prepare compensations. Tradeoffs should be expressed in terms of "gives up X to get Y", and not just a list of negatives.

*** Benefits

*** Risks

** Unknowns                                                       :optional:
After having done the research to prepare this summary, what are the key aspects that are unknown, e.g. performance characteristics under load etc.

** Indicators for Use                                         :optional:
In what circumstances is this service a good fit and why?

** Contra-indicators                                     :optional:
In what circumstances is this service a poor fit and why?
** Alternatives                                                   :optional:
Are there alternative services in the same space? In what ways do they differ, e.g. by taking on a slightly different problem set, emphasizing different aspects, or making different tradeoffs?

** Other Relevant Characteristics                                 :optional:
Are there operational (latency, scalability, security) aspects which should be highlighted?

** Resources
Please include links to any high level overviews, design documents, or presentations so people can dive deeper.
